# configure the Elasticsearch client for a cluster of two nodes
#quarkus.elasticsearch.hosts = 
#quarkus.elasticsearch.username=
#quarkus.elasticsearch.password=
What is powershell script wrapper? 
What tophat implementation reference?


Send ACK Status needs to done which component? Mostly RestartCommand
Send ACK Status needs to done which component? Mosttly RestartCommand
what does registerExecuting() do
How to state transistion happening in the RestartAtmCommand
jobId is only available after Command submits job to LSS Executor


Create Abstract Class for Command - Page 4
Create Class for CommnadRegistry - Page 8 - May be this can be named Repository in line with other LSS


Beans
Create Class for CommandParameter - Page 10
Create Class for CommandState 
Create class for CommandResult - Page 10
Create class for ValidationResult - Page 10
Create class for CommandStatus - Page 10
Create class for CommandSubStatus - Page 10

CommandFactory - Page 8
    Command createHearBeat() is main implementation


Services autowired into RestartAtmCommand through CommandFacotry
Create class for StatePersistanceService - Use file Service from lss to acheive this.
Create class for CommandStatusReporter - this class will be done my Shyam because it needs to make http calls to TM
Create class for AsyncJobExecuter -> this should be service from Executor Service, might not be needed to write from scratch.
Create Command
